apiVersion: v1
kind: ConfigMap
metadata:
  name: locustfile-cm
  namespace: demo
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class QuickUser(HttpUser):
        wait_time = between(1, 2)

        @task
        def index(self):
            self.client.get("/")