apiVersion: v1
kind: ConfigMap
metadata:
  name: locustfile-cm
  namespace: demo
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class QuickUser(HttpUser):
        wait_time = between(1, 2)

        @task(5)
        def index(self):
            self.client.get("/index.html")

        @task(3)
        def about(self):
            self.client.get("/about.html")

        @task(1)
        def contact(self):
            self.client.get("/contact.html")
